"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// import path from "path";
// import { config } from "dotenv";
// config({ path: path.join(__dirname, "../.env") });
require("dotenv/config");
var express_1 = require("express");
var cors_1 = require("cors");
var error_1 = require("./middlewares/error");
var todo_route_1 = require("./routes/todo-route");
var notFound_1 = require("./middlewares/notFound");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use("/todo", todo_route_1.default);
app.use(notFound_1.default);
app.use(error_1.default);
var port = process.env.PORT;
app.listen(port, function () { return console.log("Server is running on port ".concat(port)); });
